### ISSUE TITLE
TLS session resumption decreases privacy

### ISSUE THREAD

**Issue by jedisct1** [Jigsaw-Code/Intra#101]
Intra seems to support TLS session resumption.

This mechanism can be used to link queries to devices. So that individual devices between NAT can be fingerprinted. More importantly, different IP addresses can be linked to the same device (in particular: VPN IP addresses can be associated to the real client IP).

This effectively *reduces* privacy over standard DNS, giving more information to DNS operators.

Intra should allow disabling TLS session resumption.

**Comment by bemasc** [comment]
TLS session resumption links queries to each other, by the fact that they were processed in the same TLS session.  Even without TLS session resumption, this linking is already possible due to socket reuse.  All DNS over HTTPS and DNS over TLS clients must reuse a socket for multiple successive queries to achieve acceptable query latency.  Thus, the server can already identify that these queries were performed by a single device.

When we talk about session resumption, we are trading between the duration of query linkability and the degree of performance impairment.

Rather than focus on query linkability, which is largely unavoidable (especially on IPv6 networks where NAT is no longer present), Intra's purpose is to enable users to choose a DNS server that they trust.  An option to enable or disable session resumption seems unlikely to be comprehensible by anyone other than a TLS expert, so I don't think it's a good fit for a tool that's designed for a general audience.

**Comment by jedisct1** [comment]
dnscrypt-proxy has a setting with a simple description that doesn't require being a TLS expert to understand:

```toml
## DoH: Disable TLS session tickets - increases privacy but also latency

# tls_disable_session_tickets = false
```

and for DNSCrypt:

```toml
## DNSCrypt: Create a new, unique key for every single DNS query
## This may improve privacy but can also have a significant impact on CPU usage

# dnscrypt_ephemeral_keys = false
```

Users don't have any problem understanding this either, and have been using it a lot. As well as routing the queries through Tor. Fingerprinting client devices can be valuable for Google, but for a tool whose main purpose to improve privacy, speed should not be the first priority. Or at least, give users a choice.
