### ISSUE TITLE
NullPointerException - IoBridge.postRecvfrom

### ISSUE THREAD

**Issue by fortuna** [Jigsaw-Code/Intra#160]
Firebase shows a MullPointerException happening:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.net.InetAddress.equals(java.lang.Object)' on a null object reference
libcore.io.IoBridge.postRecvfrom (IoBridge.java:639)
libcore.io.IoBridge.recvfrom (IoBridge.java:611)
java.net.PlainDatagramSocketImpl.doRecv (PlainDatagramSocketImpl.java:152)
java.net.PlainDatagramSocketImpl.receive0 (PlainDatagramSocketImpl.java:140)
java.net.AbstractPlainDatagramSocketImpl.receive (AbstractPlainDatagramSocketImpl.java:143)
java.net.DatagramSocket.receive (DatagramSocket.java:847)
sockslib.server.UDPRelayServer.run (UDPRelayServer.java:151)
java.lang.Thread.run (Thread.java:764)
```

**Comment by bemasc** [comment]
Current best guess:
 1. In 'recvfrom' (IoBridge.java), `packet` is non-null, so `srcAddress is an empty address object.
```java
InetSocketAddress srcAddress = packet != null ? new InetSocketAddress() : null;
```
This object is supposed to be populated by Libcore.os.recvfrom in the next line:
```java
result = Libcore.os.recvfrom(fd, bytes, byteOffset, byteCount, flags, srcAddress);
```
 2. Libcore.os.recvfrom calls `Linux_recvFromBytes` (libcore_io_Linux.cpp), which was [changed in Android N](https://android.googlesource.com/platform/libcore/+/6dd21e692ae87b75e49b23ffbecc6964604f466a%5E%21/).
 3. According to that comment, if the socket has already shut down, `srcAddress` will not be populated.
 4. `postRecvFrom`(IoBridge.java) throws a NullPointerException because `srcAddress` is non-null but not populated (i.e. `srcAddress.getAddress()` is null).

I'm not sure what to do about this, other than to file a bug report and wrap this call in a `try {}`.
