### ISSUE TITLE
Provide a way to clear DNS cache

### ISSUE THREAD

**Issue by dgulinobw** [Jigsaw-Code/Intra#204]
Currently there is no way to clear the DNS cache when using Intra.
One can do this with the native Android DNS cache by changing wifi networks or enable/disabling wifi.  Disabling Intra does not clear it's DNS cache.

One can test this with this site:
http://dnscookie.com/

**Comment by bemasc** [comment]
Intra doesn't have its own DNS cache, but it's possible that the Android DNS cache is not clearing as it normally would, because it's associated with the long-lived VPN interface that Intra creates.  You can clear the cache by disabling and re-enabling Intra.

We might be able to approximate Android's cache clearing behavior by re-establishing the VPN after network change events.  (Android theoretically supports atomic re-establishment of the VPN, although when I've tried this previously I've encountered some misbehavior.)

**Comment by payangf** [comment]
Why not t.func clearcache. Yes?

**Comment by bemasc** [comment]
Intra does not have a cache, and cannot instruct the OS to clear its cache, so there is no action possible here.
