### ISSUE TITLE
Combine into another apps

### ISSUE THREAD

**Issue by senyung** [Jigsaw-Code/Intra#244]
Sorry if this in wrong category. Could we include Intra VPN in our own APK ?  

I have an apps using webview but the host address is block by ISP. And don't feel right to ask user to open the vpn first then my apps, 

My research so for, I am stuck at GoVPNAdapter.java, establishVpn method
Why .addDisallowedApplication(vpnService.getPackageName()) in  ? if remove this line VPN simply wont work.

Any comment will be very appreciate

best regarts
Sen

**Comment by bemasc** [comment]
`addDisallowedApplication` is used to allow Intra's own sockets to escape from the VPN.  Otherwise, it would try to route all traffic back into itself.  You can try to use "socket protection" instead (getProtector() in GoVpnAdapter), but this quickly becomes very complicated.

If you're only trying to protect traffic from your own WebView, you might be better off not using a VPN.  Instead, you should be able to configure the WebView to use a proxy server.  You could point the webview to an instance of the proxy server that was used in earlier versions of Intra: https://github.com/Jigsaw-Code/Intra/blob/174e64fa6cb9a9849fea7115cf4cc31be4cc02d0/Android/app/src/main/java/app/intra/net/socks/SocksVpnAdapter.java#L131

**Comment by senyung** [comment]
thank for the response, its very good tips. Thanks again
