### ISSUE TITLE
New DNS Providers / Codes / Kody

### ISSUE THREAD

**Issue by cjhenck** [Jigsaw-Code/Intra#363]
Please use this issue for all suggestions of new DNS providers for Intra

**Comment by cjhenck** [comment]
These servers were suggested in the referenced threads. I am copying them here to consolidate them for future review only; they have not been checked or vetted in any way:

https://dns.hostux.net/dns-query
https://dns.adguard.com/dns-query
https://dns.hinet.net/dns-query
https://doh.westus.pi-dns.com/dns-query
https://ibuki.cgnat.net/dns-query
https://doh-2.seby.io/dns-query
https://tmtaer.biz/dns-query
https://hk-dns.233py.com/dns-query
https://fastbravedns.com/
https://233py.com/dns-query
https://m.arkansso.com/dns-query
https://doh.360.cn/dns-query
https://kozmapat.mezib.com/dns-query
https://dns-nyc.aaflalo.me/dns-query
https://dns1.quickline.ch/dns-query
https://ibksturm.synology.me/dns-query
https://doh.centraleu.pi-dns.com/dns-query
https://resolver-eu.lelux.fi/dns-query
https://eu1.dns.lavate.ch/dns-query
https://dns-family.adguard.com/dns-query
https://dns.east.comss.one/dns-query
https://doh.eastas.pi-dns.com/dns-query
https://dns.quickline.ch/dns-query
https://dns.trli.club/dns-query
https://dns.wcc.best/dns-query
https://deic-lgb.anycast.censurfridns.dk/
https://bravedns.com/configure
https://arashi.doh.pp.ua/dns-query
https://m.winline.ru/dns-query
https://us1.dns.lavate.ch/dns-query
https://mendeyok.dns.com/dns-query
https://sizdebarmy.intrakod.com/dns-query
https://bolsaberayin.dns.ch/dns-query
https://dns2.quickline.ch/dns-query
https://cubedns.com/dns-query
https://dns.bentasker.co.uk/dns-query
https://dns.alidns.com/dns-query
https://doh.ffmuc.net/dns-query
https://kracon.anycast.censurfridns.dk/dns-query
https://tigobusiness.com.ni/doh
https://tr.pinterest.com/dns-query
https://deic-ore.anycast.censurfridns.dk/

All from:
https://dnscrypt.info/public-servers

**Comment by Rusikjan** [comment]
где взять код интры напишите пожалуйста

**Comment by Shatlyktmt** [comment]
Men bar intra code

**Comment by Shatlyktmt** [comment]
Kim3 kod gerek

**Comment by Nabelliyigit** [comment]
> 



> Please use this issue for all suggestions of new DNS providers for Intra

Intra kod bar bolsa su yere yazayyn

**Comment by Nabelliyigit** [comment]
Intra kod gerek

**Comment by Serdar04wiwiwi** [comment]
Intra kot bami

**Comment by Serdar04wiwiwi** [comment]
Intra kot bami

**Comment by Sohbet2005** [comment]
Intra kod bami sizde

**Comment by Ezi-lang** [comment]
Ba gerekmi

пн, 31 янв. 2022 г., 14:20 Serdar04wiwiwi ***@***.***>:

**Comment by Sohbet2005** [comment]
Salowmaleykim ugradai agam bar bolsa

вс, 29 мая 2022 г., 10:45 Ezi-lang ***@***.***>:

**Comment by Sohbet2005** [comment]
Ugradai agam bar bolsa intran kody

**Comment by Atageldi481** [comment]
İntra kody barmy

**Comment by skr3c** [comment]
https://dns.skrzypiec.pl/dns-query
My private server. Blocks ads, trackers and phishing sites.

**Comment by KS-OTO** [comment]
Hello,  developer.
This is a suggestion regarding the addition of a DNS provider:
Currently, multiple DNS providers are built into intra for users to freely choose from. However, all the built-in DNS providers mentioned above are limited by some objective reasons, and basically none of them can provide a good experience in the network environment in mainland China; as a result, users in mainland China find it difficult to directly enjoy the convenience of the APP function design with the help of the built-in providers in intra, and instead need to configure the custom DNS provider function independently, but this is a decline in the user experience.
Therefore, it is recommended that you can build my maintained DoH service for users in mainland China into the intra APP: 18bit DNS.
The public welfare free DNS service of 18bit was created in March 2022 and has been running smoothly until now, with more than 940 million DNS requests resolved daily;
Moreover, the 18bit official has been recommending to users to use the DNS service provided by 18bit with the help of the intra APP and providing the hosted download service and usage tutorial of the intra APP since its establishment;
Today, I hope to upgrade the experience of this part of users once again. For this reason, I raise this issue, hoping that the built-in DNS provider of intra can include the 18bit DNS service to improve the experience of users in mainland China;
18bit website: https://www.18bit.cn
DOH line: https://doh.18bit.cn/dns-query

--------------------------------------------------
你好，开发者。
这是一条关于新增DNS提供商的建议：
当前intra内置了多个DNS提供商供用户自由选择，但上述的所有内置的DNS提供商受限于一些客观原因，均在中国大陆的网络环境下基本都无法提供良好的体验；为此中国大陆的用户很难借助intra内置提供商直接享受APP功能设计的便利性，转而需要自主配置自定义DNS提供商功能，但这对用户体验是下降的。

为此建议你能在intra APP中内置我运维的面向中国大陆用户的DoH服务：18bit
18bit的公益免费DNS服务从2022年3月创建，平稳运行至今，每日解析DNS请求数超过9.4亿条；
并且，18bit官方从创立至今就在向用户推荐借助使用intra APP来使用18bit提供的DNS服务，并提供intra APP的托管下载服务和使用教程；
今天，我希望能让这部分用户体验再升级一次，为此提出这条issues，希望intra的内置DNS供应商能包含18bit DNS服务以提高中国大陆用户的体验；

18bit官网：www.18bit.cn
DOH线路：https://doh.18bit.cn/dns-query

**Comment by KS-OTO** [comment]
@fortuna

**Comment by KS-OTO** [comment]
@fortuna Please take some time to review this issue

**Comment by ngasanay237-droid** [comment]
Please help give me outline code
